### ISSUE TITLE
Dependencies change PRs by Dependabot are automerged 

### ISSUE THREAD

**Issue by rluvaton** [fastify/.github#15]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

PRs created by Dependabot are automerged even if they contain breaking change this is  dangerous as it could break the build

__Originally posted by @rluvaton in https://github.com/fastify/fastify-rate-limit/pull/219#issuecomment-1039891478__

**Comment by rluvaton** [comment]
The issue is the `target: minor` option in the automerge configuration.

Would you mind integrating this: https://github.com/fastify/workflows/ ?
So we will bypass this issue.



__Originally posted by @Eomm in https://github.com/fastify/fastify-rate-limit/pull/219#issuecomment-1039982677__

I don't have much time now so I'm opening a new issue instead of fixing this

I suggest you add the `good-first-issue` label

**Comment by mcollina** [comment]
I don't think we should do this. If a dependency bumps a major but our tests won't break.. why should we not land it? I would land it even if wasn't automerged.

**Comment by rluvaton** [comment]
If there is a breaking change I think it should be looked up manually, as in case we missed testing it it wouldn't break our build

**Comment by mcollina** [comment]
We maintain more than 50 modules in this organization and we would use any possible means to reduce the workload on the team.

You come to our organization asking we validate dependency updates that pass our test suite manually. However you do not have the time to make a 1 line change.

Let me propose a deal: I'm happy to land this change if you review all semver-major dependency changes in the org, manually.
Are you in?

**Comment by rluvaton** [comment]
I sense from your comment a hostile tone, maybe I wrote something that offend you? If so, I did not mean like that, I hope you can see that I'm willing to contribute to this project and happy to help

**Comment by rluvaton** [comment]
And in your reusable workflow you did use the `minor` only https://github.com/fastify/workflows/blob/79f3bba3d3a3be7d72dbb8106ded8d724d50fe0a/.github/workflows/plugins-ci.yml#L61

**Comment by rluvaton** [comment]
Wait, haven't I opened this issue in `fastify-rate-limit` repo? 😨😅

**Comment by mcollina** [comment]
> I sense from your comment a hostile tone, maybe I wrote something that offend you? If so, I did not mean that, I hope you can see that I'm willing to contribute to this project and happy to help

I'm sorry if I was a bit harsh. Let me explain a bit better.

You stated:

> If so this is extremely dangerous that it auto merge dependency with breaking changes

On a PR that had all tests passing.

What are the alternatives?

1) semver-major dependencies are not updated, making further upgrades harder (two or more semver-majors down the line).
2) a maintainer has to spend time doing validating the change, looking at the changelog to understand if there was an important change.

Given _never updating_ is not acceptable, you are arguing we spend more of our time manually checking the dependencies. However, __you have no right in telling us how we should spend our time__. Why would you do so? Would it be ok for you if a stranger stop you on the street to tell you what to do with your time?

I would also note that all the interactions showed a significant level of entitlement from yourself, because [you had not time to do a simple fix](https://github.com/fastify/fastify-rate-limit/pull/219#issuecomment-1046074180).

---

I can have this discussion with @Eomm, @jsumners or any other collaborators because they have dedicated enough time to this project showing that they _care_. They are collaborators and they are entitled to an opinion on this matter. As an example, they can _volunteer_ to do more of this kind work if they feel it's needed.

**Comment by rluvaton** [comment]
Fair enough @mcollina have a great day and hope to contribute more soon...
